**Metody stack() i unstack()**

In [1]:
import pandas as pd
import numpy as np

In [2]:
incidents = pd.read_csv('C:/Users/Mariusz Baran/Data_Science_kurs/Data_science_pliki/course-files/Canadian Railway Crossing Incidents.csv')
incidents.set_index(['Region', 'EventType'], inplace=True)
incidents.sort_index(inplace=True)
incidents.head(10)

                                   Public automated  Public passive  Private  \
Region           EventType
Alberta          Accidents                        3               7        2
                 Fatalities                       0               0        0
                 Serious injuries                 0               1        2
British Columbia Accidents                        4               1        0
                 Fatalities                       0               0        0
                 Serious injuries                 3               0        0
Manitoba         Accidents                        1               3        0
                 Fatalities                       0               1        0
                 Serious injuries                 0               0        0
New Brunswick    Accidents                        0               0        0

                                   Farm
Region           EventType
Alberta          Accidents            0
                 Fatalities           0
                 Serious injuries     0
British Columbia Accidents            0
                 Fatalities           0
                 Serious injuries     0
Manitoba         Accidents            2
                 Fatalities           0
                 Serious injuries     1
New Brunswick    Accidents            0

Metoda stack bierze wewnÄ™trzny poziom kolumn i przepisuje go do wierszy

In [3]:
incidents.stack().head()

Region   EventType
Alberta  Accidents   Public automated    3
                     Public passive      7
                     Private             2
                     Farm                0
         Fatalities  Public automated    0
dtype: int64

Zapisanie do data frame

In [5]:
incidents.stack().to_frame().head()

                                     0
Region  EventType
Alberta Accidents  Public automated  3
                   Public passive    7
                   Private           2
                   Farm              0
        Fatalities Public automated  0

In [6]:
stack_incidents = incidents.stack().to_frame()

In [7]:
stack_incidents.head()

                                     0
Region  EventType
Alberta Accidents  Public automated  3
                   Public passive    7
                   Private           2
                   Farm              0
        Fatalities Public automated  0

Metoda unstack() dziaÅ‚a odwrotnie

In [8]:
stack_incidents.unstack().head()

                                                 0
                                  Public automated Public passive Private Farm
Region           EventType
Alberta          Accidents                       3              7       2    0
                 Fatalities                      0              0       0    0
                 Serious injuries                0              1       2    0
British Columbia Accidents                       4              1       0    0
                 Fatalities                      0              0       0    0

In [9]:
stack_incidents.unstack().unstack().head()

                                0                                             \
                 Public automated                             Public passive
EventType               Accidents Fatalities Serious injuries      Accidents
Region
Alberta                         3          0                0              7
British Columbia                4          0                3              1
Manitoba                        1          0                0              3
New Brunswick                   0          0                0              0
Newfoundland                    0          0                0              0

                                                                   \
                                               Private
EventType        Fatalities Serious injuries Accidents Fatalities
Region
Alberta                   0                1         2          0
British Columbia          0                0         0          0
Manitoba                  1                0         0          0
New Brunswick             0                0         0          0
Newfoundland              0                0         0          0


                                       Farm
EventType        Serious injuries Accidents Fatalities Serious injuries
Region
Alberta                         2         0          0                0
British Columbia                0         0          0                0
Manitoba                        0         2          0                1
New Brunswick                   0         0          0                0
Newfoundland                    0         0          0                0

DomyÅ›lnie level=-1 ale moÅ¼na wpisaÄ‡ inny albo sÅ‚ownie nazwÄ™

In [10]:
stack_incidents.unstack(0).head()

                                  0                                          \
Region                      Alberta British Columbia Manitoba New Brunswick
EventType
Accidents  Public automated       3                4        1             0
           Public passive         7                1        3             0
           Private                2                0        0             0
           Farm                   0                0        2             0
Fatalities Public automated       0                0        0             0

                                                                            \
Region                      Newfoundland Northwest Territories Nova Scotia
EventType
Accidents  Public automated            0                     0           1
           Public passive              0                     0           0
           Private                     0                     0           0
           Farm                        0                     0           0
Fatalities Public automated            0                     0           0


Region                      Ontario Quebec Saskatchewan
EventType
Accidents  Public automated       7      4            1
           Public passive         0      0            3
           Private                2      1            0
           Farm                   0      0            0
Fatalities Public automated       1      1            0

In [11]:
stack_incidents.unstack(level='Region').head()

                                  0                                          \
Region                      Alberta British Columbia Manitoba New Brunswick
EventType
Accidents  Public automated       3                4        1             0
           Public passive         7                1        3             0
           Private                2                0        0             0
           Farm                   0                0        2             0
Fatalities Public automated       0                0        0             0

                                                                            \
Region                      Newfoundland Northwest Territories Nova Scotia
EventType
Accidents  Public automated            0                     0           1
           Public passive              0                     0           0
           Private                     0                     0           0
           Farm                        0                     0           0
Fatalities Public automated            0                     0           0


Region                      Ontario Quebec Saskatchewan
EventType
Accidents  Public automated       7      4            1
           Public passive         0      0            3
           Private                2      1            0
           Farm                   0      0            0
Fatalities Public automated       1      1            0

MoÅ¼na wiÄ™cej niÅ¼ jednÄ… kolumnÄ™

In [12]:
stack_incidents.unstack(level=['Region', 'EventType']).head()

                         0                                               \
Region             Alberta                             British Columbia
EventType        Accidents Fatalities Serious injuries        Accidents
Public automated         3          0                0                4
Public passive           7          0                1                1
Private                  2          0                2                0
Farm                     0          0                0                0

                                                                   \
Region                                        Manitoba
EventType        Fatalities Serious injuries Accidents Fatalities
Public automated          0                3         1          0
Public passive            0                0         3          1
Private                   0                0         0          0
Farm                      0                0         2          0

                                                 ...                   \
Region                            New Brunswick  ...      Nova Scotia
EventType        Serious injuries     Accidents  ... Serious injuries
Public automated                0             0  ...                0
Public passive                  0             0  ...                0
Private                         0             0  ...                0
Farm                            1             0  ...                0

                                                                             \
Region             Ontario                                Quebec
EventType        Accidents Fatalities Serious injuries Accidents Fatalities
Public automated         7          1                1         4          1
Public passive           0          0                0         0          0
Private                  2          0                0         1          0
Farm                     0          0                0         0          0


Region                            Saskatchewan
EventType        Serious injuries    Accidents Fatalities Serious injuries
Public automated                0            1          0                0
Public passive                  0            3          0                0
Private                         0            0          0                0
Farm                            0            0          0                0

[4 rows x 30 columns]

Wyszukiwanie

In [13]:
stack_incidents.head()

                                     0
Region  EventType
Alberta Accidents  Public automated  3
                   Public passive    7
                   Private           2
                   Farm              0
        Fatalities Public automated  0

In [15]:
stack_incidents.loc[('Alberta', 'Accidents', 'Private'), 0]

2